remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: Awesome Algorand
tagline: Curated resources from Algorand Blockchain ecosystem
description: ⚡ An awesome list about everything related to the Algorand Blockchain ⛓
google_analytics: G-HS5HNLQJRH
image: https://i.imgur.com/l8eg1n9.png

twitter:
  username: millionalgos
